# Generated by Django 4.2.6 on 2023-10-14 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('active_ingredient', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('dosage_form', models.CharField(max_length=255)),
                ('unit_price', models.CharField(max_length=255)),
                ('stock_quantity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.CharField(max_length=100)),
                ('prescription_date', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('modification_date', models.CharField(max_length=255)),
                ('modification_type', models.CharField(choices=[('Add', 'Thêm mới'), ('Edit', 'Sửa đổi'), ('Delete', 'Xóa')], max_length=10)),
                ('modified_by', models.EmailField(max_length=255)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='DoseChecking',
            fields=[
                ('dose_check_id', models.AutoField(primary_key=True, serialize=False)),
                ('checked_date', models.CharField(max_length=255)),
                ('is_dosage_correct', models.BooleanField()),
                ('comments', models.CharField(max_length=255)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.prescription')),
            ],
        ),
    ]
