# Generated by Django 4.2.6 on 2023-10-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosechecking',
            name='checked_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dosechecking',
            name='comments',
            field=models.TextField(),
        ),
    ]
